export const enum EErrorMessages {
  USER_NOT_FOUND = 'User not found',
  ROOM_NOT_FOUND = 'Room not found',
  ROOM_NOT_ALLOWED = 'Room editing is not allowed',
  ROOM_IS_IN_PROGRESS = 'Room is in progress',
  PASSWORD_DOESNT_MATCH = 'Passwords do not match',
  USER_ALREADY_EXISTS = 'User already exists',
  ROOM_ALREADY_EXISTS = 'Room already exists',
  ROOM_ALREADY_STARTED = 'Room already started',
  ALREADY_IN_ROOM = 'User is already in room',
  ROOM_IS_FULL = 'Room is full',
  NOT_IN_ROOM = 'You are not in this room',
  CANNOT_EXIT_STARTED_GAME = 'Cannot exit from started game',
  USER_NOT_FOUNT_IN_LEADERBOARD = 'User not found in leaderboard',
  NOT_ENOUGH_PLAYERS = 'Not enough players to start the game',
  PLAYER_NOT_FOUND_IN_GAME = 'Player not found in this game',
  PLAYER_NOT_FOUND = 'Player not found',
  PLAYER_IS_NOT_IN_ROOM = 'Player is not in this room',
  INVALID_PLAYER_TARGET = 'Invalid player target',
  CARD_NOT_IN_HAND = 'Card not in hand',
  GAME_NOT_FOUND = 'Game not found',
  INVALID_ROW_CHOSEN = 'Invalid row chosen',
  NO_CARD_SELECTED = 'No card selected',
  NO_ROOM_STATS = 'No stats for current room',
  ACTIVE_GAME_NOT_FOUND = 'Active game not found',
  ROOM_WITHOUT_PASSWORD = 'Room is private but has no password',
  MESSAGE_NOT_FOUND = 'Message not found',
  MESSAGE_FORBIDDEN = 'Cannot edit others messages',
  MESSAGE_FORBIDDEN_DELETED = 'Cannot edit deleted message',
  MESSAGE_ALREADY_DELETED = 'Message already deleted',

  NOTIFICATION_NOT_FOUND = 'Not found notification with id',
  NOT_ALLOWED_SELF_FRIEND = 'Cannot add yourself as a friend',
  FRIENDS_REQUEST_NOT_FOUND = 'Request not found',
  NOT_YOUR_FRIENDS = 'You are not a friends',
}
